### PR TITLE
updating expected converted value on each error detected

### PR DESCRIPTION
**Pull request by doorooful**
- for Converter > "상세변환"
- Updated detailed error information with key uvalue(user-defined-value)
- Updated converted_highlighted_sentences to mark if it's cvalue(from server) or uvalue(from user)
- tested: updating multiple user values

### CODE REVIEW

**Comment by doorooful** [comment]
### Sample body where did=143:

```JSON
{
    "143": {
        "0": {
            "typo": {
                "0": "이것은",
                "1": "기록해"
            }
        },
        "2": {
            "typo": {
                "0": "테스팅을"
            },
            "slang": {
                "0": "sibal"
            }
        },
        "4": {
            "pdd": {
                "0": "010-0000-0000"
            }
        }
    }
}
```

**Comment by doorooful** [comment]
### Sample returning from `http://127.0.0.1:5001/api/converter/convreport`
```JSON
{
    "did": 143,
    "dname": "fake.txt",
    "overview_rate": "50.96%",
    "active_module": [
        "typo",
        "slang",
        "dup",
        "pdd",
        "spc"
    ],
    "module_count": {
        "typo": 6,
        "slang": 1,
        "dup": 1,
        "pdd": 2,
        "spc": 1
    },
    "contents": "이겅 일부러 오탈자를 만들 어 놓은 거시다.\n띄어쓰기를안한문장이다. \n시발 이건 욕설 테스팅을 위한 문장이다. \n내 주민번호는 사실 980216-1234567 이거다. \n010-1234-5678로 연락해라! \n동일 한 문장을 써보자. \n동일 한 문장을 써보자. \n⭐ 이모지야. ",
    "converted_dname": "fake_filtered.txt",
    "converted_contents": "이것은 일부러 오탈자를 기록해 놓은 것이다.\n띄어쓰기를 안 한 문장이다. \nsibal 이건 욕설 테스팅을 위한 문장이다. \n내 주민등록번호는 사실 ******-******* 이거다. \n010-0000-0000로 연락해라! \n동일 한 문장을 써보자. \n:별: 이모지야. ",
    "sentences": [
        "<mark id='typo'>이겅</mark> 일부러 오탈자를 <mark id='typo'>만들 어</mark> <mark id='typo'>놓은 거시다</mark>.",
        "<mark id='typo'>띄어쓰기를안한문장이다</mark>. ",
        "<mark id='slang'>시발</mark> 이건 욕설 <mark id='typo'>테스팅을</mark> 위한 문장이다. ",
        "내 <mark id='typo'>주민번호는</mark> 사실 <mark id='pdd'>980216-1234567</mark> 이거다. ",
        "<mark id='pdd'>010-1234-5678</mark>로 연락해라! ",
        "동일 한 문장을 써보자. ",
        "<mark id='dup'>동일 한 문장을 써보자. </mark>",
        "<mark id='spc'>⭐</mark> 이모지야. "
    ],
    "details": {
        "0": {
            "type": [
                "typo"
            ],
            "original_highlighted_sentences": "<mark id='typo'>이겅</mark> 일부러 오탈자를 <mark id='typo'>만들 어</mark> <mark id='typo'>놓은 거시다</mark>.",
            "converted_highlighted_sentences": "<mark id='typo' converted_type='uvalue'>이것은</mark> 일부러 오탈자를 <mark id='typo' converted_type='uvalue'>기록해</mark> <mark id='typo' converted_type='cvalue'>놓은 것이다</mark>.",
            "error_info": {
                "typo": {
                    "0": {
                        "dvalue": "이겅",
                        "cvalue": "이건",
                        "uvalue": "이것은",
                        "desc": ""
                    },
                    "1": {
                        "dvalue": "만들 어",
                        "cvalue": "만들어",
                        "uvalue": "기록해",
                        "desc": ""
                    },
                    "2": {
                        "dvalue": "놓은 거시다",
                        "cvalue": "놓은 것이다",
                        "uvalue": "",
                        "desc": ""
                    }
                }
            }
        },
        "1": {
            "type": [
                "typo"
            ],
            "original_highlighted_sentences": "<mark id='typo'>띄어쓰기를안한문장이다</mark>. ",
            "converted_highlighted_sentences": "<mark id='typo' converted_type='cvalue'>띄어쓰기를 안 한 문장이다</mark>. ",
            "error_info": {
                "typo": {
                    "0": {
                        "dvalue": "띄어쓰기를안한문장이다",
                        "cvalue": "띄어쓰기를 안 한 문장이다",
                        "uvalue": "",
                        "desc": ""
                    }
                }
            }
        },
        "2": {
            "type": [
                "typo",
                "slang"
            ],
            "original_highlighted_sentences": "<mark id='slang'>시발</mark> 이건 욕설 <mark id='typo'>테스팅을</mark> 위한 문장이다. ",
            "converted_highlighted_sentences": "<mark id='slang' converted_type='uvalue'>sibal</mark> 이건 욕설 <mark id='typo' converted_type='uvalue'>테스팅을</mark> 위한 문장이다. ",
            "error_info": {
                "typo": {
                    "0": {
                        "dvalue": "테스팅을",
                        "cvalue": "검증을",
                        "uvalue": "테스팅을",
                        "desc": ""
                    }
                },
                "slang": {
                    "0": {
                        "dvalue": "시발",
                        "cvalue": "**",
                        "uvalue": "sibal",
                        "desc": ""
                    }
                }
            }
        },
        "3": {
            "type": [
                "typo",
                "pdd"
            ],
            "original_highlighted_sentences": "내 <mark id='typo'>주민번호는</mark> 사실 <mark id='pdd'>980216-1234567</mark> 이거다. ",
            "converted_highlighted_sentences": "내 <mark id='typo' converted_type='cvalue'>주민등록번호는</mark> 사실 <mark id='pdd' converted_type='cvalue'>******-*******</mark> 이거다. ",
            "error_info": {
                "typo": {
                    "0": {
                        "dvalue": "주민번호는",
                        "cvalue": "주민등록번호는",
                        "uvalue": "",
                        "desc": ""
                    }
                },
                "pdd": {
                    "0": {
                        "dvalue": "980216-1234567",
                        "cvalue": "******-*******",
                        "uvalue": "",
                        "desc": "주민등록번호"
                    }
                }
            }
        },
        "4": {
            "type": [
                "pdd"
            ],
            "original_highlighted_sentences": "<mark id='pdd'>010-1234-5678</mark>로 연락해라! ",
            "converted_highlighted_sentences": "<mark id='pdd' converted_type='uvalue'>010-0000-0000</mark>로 연락해라! ",
            "error_info": {
                "pdd": {
                    "0": {
                        "dvalue": "010-1234-5678",
                        "cvalue": "010-****-****",
                        "uvalue": "010-0000-0000",
                        "desc": "전화번호"
                    }
                }
            }
        },
        "6": {
            "type": [
                "dup"
            ],
            "original_highlighted_sentences": "<mark id='dup'>동일 한 문장을 써보자. </mark>",
            "converted_highlighted_sentences": "<del><mark id='dup'>동일 한 문장을 써보자. </mark></del>",
            "error_info": {
                "dup": 1
            }
        },
        "7": {
            "type": [
                "spc"
            ],
            "original_highlighted_sentences": "<mark id='spc'>⭐</mark> 이모지야. ",
            "converted_highlighted_sentences": "<mark id='spc' converted_type='cvalue'>:별:</mark> 이모지야. ",
            "error_info": {
                "spc": {
                    "0": {
                        "dvalue": "⭐",
                        "cvalue": ":별:",
                        "uvalue": "",
                        "desc": "emoji"
                    }
                }
            }
        }
    }
}
```

**Comment by doorooful** [comment]
### How to use:
1. Upload file
Screenshot 2023-11-19 at 10 05 44 PM

2. Fetch detected information to check did and error information
- Check did
image
- Check sid, module, error number
image

3. Update expected converted value
image

4. Get updated conv data
Screenshot 2023-11-19 at 10 13 21 PM

**Review by yoouung — APPROVED** [review]
LGTM!!

**Pull request merged**
