### PR TITLE
add delete file function

### PR DESCRIPTION
**Pull request by yoouung**
- frontend
  - add delete buttons for each files
- backend
  - add `filter/delete` api
  - add update database function

### CODE REVIEW

**Review by doorooful — CHANGES_REQUESTED** [review]
Please find the comments.
Also can you attach result video here? for the verification purpose.

In addition, it'd be better to add sequence diagram in this pr.

``` sample.pu
@startuml
title single file deletion
-> App: delete()
App -> DB: delete_file(did)
DB --> App: OK
<-- App: "SUCCESS"
@enduml
```

**Comment by yoouung** [comment]
### Demo video
https://github.com/doorooful/CapstoneProject/assets/78146904/1a924caf-2359-4915-8883-07a91415a480

**Review by doorooful — APPROVED** [review]
LGTM!

**Comment by yoouung** [comment]
### Demo video for upload and delete before module processing

https://github.com/doorooful/CapstoneProject/assets/78146904/99e14f4e-348c-4a17-845c-910c3e2929b7

**Pull request merged**
