### PR TITLE
Detection report creation

### PR DESCRIPTION
**Pull request by doorooful**
- Added detection report template
- Defined API endpoint for detection report template
- TODO: data creation flow must be refactored on milestone3

### CODE REVIEW

**Comment by doorooful** [comment]
Please find the sample report
- Using every modules
[검출-전체모듈선택.pdf](https://github.com/doorooful/CapstoneProject/files/12708336/-.pdf)

- Using 3 modules
[검출-일부모듈선택.pdf](https://github.com/doorooful/CapstoneProject/files/12708335/-.pdf)

**Review by leeinsunny — COMMENTED** [review]
Thank you for your long effortㅎㅎ

**Comment by doorooful** [comment]
Template:
image

**Comment by doorooful** [comment]
Template:

Screenshot 2023-09-25 at 3 57 00 PM

**Comment by leeinsunny** [comment]
I also think removing statistics is better!!

**Review by leeinsunny — APPROVED** [review]
Thank for your long effort!

**Pull request merged**
