### PR TITLE
Handle slang module by Insun

### PR DESCRIPTION
**Pull request by leeinsunny**
1. I correct the part of modules/slang/run.py
- I make sorting to represent '*'
2. I upload slang dictionary v2

### CODE REVIEW

**Comment by OSsunNO** [comment]
Could you upload a capture file of a related result?

**Comment by leeinsunny** [comment]
image
image

**Comment by leeinsunny** [comment]
[slang_dict_v2.xlsx](https://github.com/doorooful/CapstoneProject/files/12707709/slang_dict_v2.xlsx)

**Comment by leeinsunny** [comment]
image
image

**Review by doorooful — APPROVED** [review]
Looks good to me! ◡̈

**Pull request merged**
