### PR TITLE
information for detection report fetching from db

### PR DESCRIPTION
**Pull request by doorooful**
- DetReport class has been designed
- returning dname, active module, module count, contents from backend
- Manipulating query result to return expected data

### CODE REVIEW

**Comment by doorooful** [comment]
- Sample data returning:
``` json
{
    "did": 1,
    "dname": "demo.txt",
    "active_module": [
        "typo",
        "slang",
        "dup",
        "pdd"
    ],
    "module_count": {
        "typo": 1,
        "slang": 1,
        "dup": 1,
        "pdd": 1
    },
    "contents": "게시글 샘플 잉니다.\n이건 시발 욕설 문장이다.\n010-1234-5678로 연락해라!\n중복된 문장 입니다.\n중복된 문장 입니다.",
    "contents_with_highlights": "게시글 샘플 <mark id='typo'>잉</mark>니다.\n이건 <mark id='slang'>시발</mark> 욕설 문장이다.\n<mark id='pdd'>010-1234-5678</mark>로 연락해라!\n중복된 문장 입니다.\n<mark id='dup'>중복된 문장 입니다.</mark>"
}
```

**Comment by doorooful** [comment]
I copied previous `app.py` code lines to `app_bk.py` where every part should be implemented depend on DB connection.
Please use `python app_bk.py` for api testing regardless of DB connection.

**Comment by doorooful** [comment]
```bash
MariaDB [capstone]> select * from doc;
+-----+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------+-------+------+------+------+
| did | dname    | contents                                                                                                                                              | typo | slang | dup  | pdd  | spc  |
+-----+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------+-------+------+------+------+
|   1 | demo.txt | 게시글 샘플 잉니다.
이건 시발 욕설 문장이다.
010-1234-5678로 연락해라!
중복된 문장 입니다.
중복된 문장 입니다.                                        |    1 |     1 |    1 |    1 |    0 |
+-----+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------+-------+------+------+------+
1 row in set (0.002 sec)

MariaDB [capstone]> select * from sprocessing;
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
| sid | did | osent                              | typo                                                  | slang                                                         | dup  | pdd                                                                                   | spc  | csent |
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
|   1 |   1 | 게시글 샘플 잉니다.                | {"0": {"dvalue": "잉", "cvalue": "입", "desc": ""}}   | NULL                                                          | NULL | NULL                                                                                  | NULL | NULL  |
|   2 |   1 | 이건 시발 욕설 문장이다.           | NULL                                                  | {"0": {"dvalue": "시발", "cvalue": "**", "desc": "욕설"}}     | NULL | NULL                                                                                  | NULL | NULL  |
|   3 |   1 | 010-1234-5678로 연락해라!          | NULL                                                  | NULL                                                          | NULL | {"0": {"dvalue": "010-1234-5678", "cvalue": "010-****-****", "desc": "전화번호"}}     | NULL | NULL  |
|   4 |   1 | 중복된 문장 입니다.                | NULL                                                  | NULL                                                          |    0 | NULL                                                                                  | NULL | NULL  |
|   5 |   1 | 중복된 문장 입니다.                | NULL                                                  | NULL                                                          |    1 | NULL                                                                                  | NULL | NULL  |
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
5 rows in set (0.002 sec)

**Comment by doorooful** [comment]
- Test case 1: 한 문장에 두 종류의 module이 감지된 경우(typo:이건, slang:시발)
```bash
MariaDB [capstone]> select * from sprocessing;
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
| sid | did | osent                              | typo                                                  | slang                                                         | dup  | pdd                                                                                   | spc  | csent |
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
|   1 |   1 | 게시글 샘플 잉니다.                | {"0": {"dvalue": "잉", "cvalue": "입", "desc": ""}}   | NULL                                                          | NULL | NULL                                                                                  | NULL | NULL  |
|   2 |   1 | 이건 시발 욕설 문장이다.           | {"0": {"dvalue": "이건", "cvalue": "ㅇ", "desc": ""}}                                                  | {"0": {"dvalue": "시발", "cvalue": "**", "desc": "욕설"}}     | NULL | NULL                                                                                  | NULL | NULL  |
|   3 |   1 | 010-1234-5678로 연락해라!          | NULL                                                  | NULL                                                          | NULL | {"0": {"dvalue": "010-1234-5678", "cvalue": "010-****-****", "desc": "전화번호"}}     | NULL | NULL  |
|   4 |   1 | 중복된 문장 입니다.                | NULL                                                  | NULL                                                          |    0 | NULL                                                                                  | NULL | NULL  |
|   5 |   1 | 중복된 문장 입니다.                | NULL                                                  | NULL                                                          |    1 | NULL                                                                                  | NULL | NULL  |
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
5 rows in set (0.002 sec)
```

**Comment by doorooful** [comment]
- Test case 2: 한 문장이 한 모듈에서 여러 번 감지된 경우 && 모듈 count 여러개 가능한지 확인
``` bash
MariaDB [capstone]> select * from sprocessing;
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
| sid | did | osent                              | typo                                                  | slang                                                         | dup  | pdd                                                                                   | spc  | csent |
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
|   1 |   1 | 게시글 샘플 잉니다.                | {"0": {"dvalue": "잉", "cvalue": "입", "desc": ""}}   | NULL                                                          | NULL | NULL                                                                                  | NULL | NULL  |
|   2 |   1 | 이건 시발 욕설 문장이다.           | NULL                                                  | {"0": {"dvalue": "시발", "cvalue": "**", "desc": "욕설"}}     | NULL | NULL                                                                                  | NULL | NULL  |
|   3 |   1 | ㅁ010-1234-5678로 연락해라!          | {"0": {"dvalue": "ㅁ", "cvalue": "뭐", "desc": ""}, "1": {"dvalue": "123", "cvalue": "1234", "desc": ""}}                                                  | NULL                                                          | NULL | {"0": {"dvalue": "010-1234-5678", "cvalue": "010-****-****", "desc": "전화번호"}}     | NULL | NULL  |
|   4 |   1 | 중복된 문장 입니다.                | NULL                                                  | NULL                                                          |    0 | NULL                                                                                  | NULL | NULL  |
|   5 |   1 | 중복된 문장 입니다.                | NULL                                                  | NULL                                                          |    1 | NULL                                                                                  | NULL | NULL  |
+-----+-----+------------------------------------+-------------------------------------------------------+---------------------------------------------------------------+------+---------------------------------------------------------------------------------------+------+-------+
5 rows in set (0.002 sec)
```

**Review by yoouung — APPROVED** [review]
LGTM! thanks

**Pull request merged**
