### PR TITLE
Navbar dropdown implement

### PR DESCRIPTION
**Pull request by yoouung**
- implement dropdown for Document tab
- modify navbar layout

### CODE REVIEW

**Comment by yoouung** [comment]
### screenshot
image

### test video

https://github.com/doorooful/CapstoneProject/assets/78146904/85b83e00-f79e-4ca3-9ba1-270a581b3fea

**Comment by doorooful** [comment]
Can you add statistics?

**Comment by yoouung** [comment]
### updated version (add statistics dropdown item)
image

**Comment by yoouung** [comment]
> Can you add statistics?

### updated version (add statistics dropdown item)
image

**Pull request closed without merging**
